@url=http://localhost:8000
@auth_api=/api/auth
@jsonContent = Content-Type: application/json

### 测试服务器是否连通
get {{url}}

### 检查admin用户是否存在
get {{url}}{{auth_api}}/adminexist


### 注册admin
post {{url}}{{auth_api}}/register
{{jsonContent}}

{
  "username": "user1",
  "password": "123456"
}

### 登录
post {{url}}{{auth_api}}/login
{{jsonContent}}

{
  "username": "user1",
  "password":"123456"
}

### 测试api
GET {{url}}{{auth_api}}/isLogin
{{jsonContent}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiYXV0aG9yaXR5VHlwZSI6MTAwLCJpZCI6IjYyNGNhOTdjMTZiZjdlMWY1MDdmYmQxOSIsImlhdCI6MTY0OTk5MjM1Mn0.irMKb7O0R4TAlPiszUTMKVZcvJhXSoQq8wKO7HE5d9o

{}