@url=http://localhost:8000
@auth_api=/api/auth
@articals_api=/api/articals
@jsonContent = Content-Type: application/json
@jwtToken = Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiYXV0aG9yaXR5VHlwZSI6MTAwLCJpZCI6IjYyNGNhOTdjMTZiZjdlMWY1MDdmYmQxOSIsImlhdCI6MTY1MDQ4ODY3Mn0.lGEXQQcmmVsH5zulGuGBt06QatiYB5werAbnBdyr1yo


### 检查admin用户是否存在
get {{url}}{{auth_api}}/adminexist


### 注册admin
post {{url}}{{auth_api}}/register
{{jsonContent}}

{
  "username": "user1",
  "password": "123456"
}

### 登录
post {{url}}{{auth_api}}/login
{{jsonContent}}

{
  "username": "user1",
  "password":"123456"
}

### 检查是否登录
GET {{url}}{{auth_api}}/isLogin
{{jsonContent}}
{{jwtToken}}

{}

### 新增文章
POST {{url}}{{articals_api}}/add
{{jsonContent}}
{{jwtToken}}

{
  "title": "test2",
  "author": "user1",
  "categories": ["hello", "world"],
  "description": "这是一段描述",
  "draft": "<h2>试试效果</h2>"
}

### 发布文章
POST {{url}}{{articals_api}}/publish
{{jsonContent}}
{{jwtToken}}

{
  "id": "6260f2d53359c7eb9ae4e311"
}

### 删除文章
POST {{url}}{{articals_api}}/remove
{{jsonContent}}
{{jwtToken}}

{
  "id": "6260f5e9606cc652f4979dea"
}
